"""
Documentation generator for AI Builder.
Generates README files, module docs, and API documentation from code.
"""

import ast
import re
from pathlib import Path
from datetime import datetime
from core.logger import get_logger
from config.settings import get_config
from tools.file_reader import FileReader
from tools.file_writer import FileWriter
from utils.helpers import ensure_dir

log = get_logger("tools")


class DocGenerator:
    """Generates documentation from source code."""

    def __init__(self):
        self.config = get_config()
        self.reader = FileReader()
        self.writer = FileWriter()
        self.root_dir = Path(self.config.get("root_dir", str(Path.cwd())))
        self.docs_dir = self.root_dir / self.config.get("docs_dir", "docs")

    def generate_readme(self, project_path, project_name=None, description=None):
        """Generate a README.md for a project."""
        root = Path(project_path)
        project_name = project_name or root.name

        # Try to gather info from the project
        from tools.project_analyser import ProjectAnalyser
        analyser = ProjectAnalyser()
        analysis = analyser.analyze(project_path, deep=False, max_files=50)

        if description is None:
            description = f"{project_name} is a software project."

        lines = []
        lines.append(f"# {project_name}")
        lines.append("")
        lines.append(f"_{description}_")
        lines.append("")
        lines.append("## Overview")
        lines.append("")
        lines.append(f"- **Languages:** {', '.join(analysis.get('languages', {}).keys()) or 'N/A'}")
        lines.append(f"- **Project Types:** {', '.join(analysis.get('project_types', [])) or 'N/A'}")
        lines.append(f"- **File Count:** {analysis.get('file_count', 0)}")
        lines.append(f"- **Entry Points:** {', '.join(analysis.get('entry_points', [])) or 'N/A'}")
        lines.append("")

        # Structure
        lines.append("## Project Structure")
        lines.append("")
        lines.append("```")
        structure = analysis.get("structure", {})
        self._render_structure(structure, lines, indent=0)
        lines.append("```")
        lines.append("")

        # Dependencies
        deps = analysis.get("dependencies", [])
        if deps:
            lines.append("## Dependencies")
            lines.append("")
            for dep in deps:
                lines.append(f"- {dep['name']} ({dep['source']})")
            lines.append("")

        # Installation
        lines.append("## Installation")
        lines.append("")
        if "python" in analysis.get("project_types", []):
            lines.append("```bash")
            lines.append("pip install -r requirements.txt")
            lines.append("```")
        if "node" in analysis.get("project_types", []):
            lines.append("```bash")
            lines.append("npm install")
            lines.append("```")
        lines.append("")

        # Usage
        entry_points = analysis.get("entry_points", [])
        lines.append("## Usage")
        lines.append("")
        if entry_points:
            lines.append("```bash")
            lines.append(f"python {entry_points[0]}")
            lines.append("```")
        else:
            lines.append("Run the main entry point of the project.")
        lines.append("")

        # Testing
        lines.append("## Testing")
        lines.append("")
        if analysis.get("has_tests"):
            lines.append("```bash")
            lines.append("python -m pytest tests/")
            lines.append("```")
        else:
            lines.append("No tests are currently available.")
        lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"_Generated by AI Builder on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")
        lines.append("")

        content = "\n".join(lines)
        readme_path = root / "README.md"
        self.writer.write(readme_path, content)
        log.info(f"Generated README.md at {readme_path}")
        return str(readme_path)

    def generate_module_docs(self, project_path):
        """Generate documentation for each Python module in a project."""
        root = Path(project_path)
        docs_output_dir = self.docs_dir / "modules"
        ensure_dir(str(docs_output_dir))

        generated = []
        for py_file in root.rglob("*.py"):
            if any(skip in str(py_file) for skip in
                   ["__pycache__", ".venv", "venv", ".git", "node_modules"]):
                continue

            doc_content = self._generate_python_module_doc(py_file, root)
            if doc_content:
                rel_path = py_file.relative_to(root)
                doc_name = str(rel_path).replace("/", "_").replace(".py", ".md")
                doc_path = docs_output_dir / doc_name
                self.writer.write(doc_path, doc_content)
                generated.append(str(doc_path))

        log.info(f"Generated {len(generated)} module docs")
        return generated

    def _generate_python_module_doc(self, file_path, project_root):
        """Generate markdown documentation for a single Python file."""
        content = self.reader.read(file_path)
        if content is None:
            return None

        try:
            tree = ast.parse(content)
        except SyntaxError:
            return None

        rel_path = Path(file_path).relative_to(project_root)
        lines = []
        lines.append(f"# Module: `{rel_path}`")
        lines.append("")

        # Module docstring
        module_doc = ast.get_docstring(tree)
        if module_doc:
            lines.append("## Description")
            lines.append("")
            lines.append(module_doc)
            lines.append("")

        # Imports
        imports = []
        for node in ast.iter_child_nodes(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.append(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.append(node.module)

        if imports:
            lines.append("## Imports")
            lines.append("")
            for imp in imports:
                lines.append(f"- `{imp}`")
            lines.append("")

        # Functions
        functions = [n for n in ast.iter_child_nodes(tree) if isinstance(n, ast.FunctionDef)]
        if functions:
            lines.append("## Functions")
            lines.append("")
            for func in functions:
                self._render_function_doc(func, lines)
                lines.append("")

        # Classes
        classes = [n for n in ast.iter_child_nodes(tree) if isinstance(n, ast.ClassDef)]
        if classes:
            lines.append("## Classes")
            lines.append("")
            for cls in classes:
                self._render_class_doc(cls, lines)
                lines.append("")

        lines.append("---")
        lines.append(f"_Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")
        lines.append("")

        return "\n".join(lines)

    def _render_function_doc(self, func, lines):
        """Render function documentation."""
        args = [a.arg for a in func.args.args]
        args_str = ", ".join(args)
        lines.append(f"### `{func.name}({args_str})`")
        lines.append("")
        lines.append(f"_Line: {func.lineno}_")
        lines.append("")
        docstring = ast.get_docstring(func)
        if docstring:
            lines.append(docstring)
        else:
            lines.append("_No documentation available._")
        lines.append("")

    def _render_class_doc(self, cls, lines):
        """Render class documentation."""
        lines.append(f"### Class: `{cls.name}`")
        lines.append("")
        lines.append(f"_Line: {cls.lineno}_")
        lines.append("")
        docstring = ast.get_docstring(cls)
        if docstring:
            lines.append(docstring)
        else:
            lines.append("_No documentation available._")
        lines.append("")

        methods = [n for n in cls.body if isinstance(n, ast.FunctionDef)]
        if methods:
            lines.append("**Methods:**")
            lines.append("")
            for method in methods:
                args = [a.arg for a in method.args.args]
                args_str = ", ".join(args)
                lines.append(f"- `{method.name}({args_str})` — _Line {method.lineno}_")
            lines.append("")

    def _render_structure(self, structure, lines, indent=0):
        """Render a directory structure as a tree."""
        prefix = "  " * indent
        for name, value in structure.items():
            if isinstance(value, dict):
                lines.append(f"{prefix}{name}")
                self._render_structure(value, lines, indent + 1)
            else:
                lines.append(f"{prefix}{name}")

    def generate_api_docs(self, project_path):
        """Generate a combined API reference document."""
        root = Path(project_path)
        lines = []
        lines.append("# API Reference")
        lines.append("")
        lines.append(f"_Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")
        lines.append("")
        lines.append("---")
        lines.append("")

        for py_file in sorted(root.rglob("*.py")):
            if any(skip in str(py_file) for skip in
                   ["__pycache__", ".venv", "venv", ".git", "node_modules"]):
                continue

            content = self.reader.read(py_file)
            if content is None:
                continue

            try:
                tree = ast.parse(content)
            except SyntaxError:
                continue

            rel_path = py_file.relative_to(root)
            lines.append(f"## `{rel_path}`")
            lines.append("")

            for node in ast.iter_child_nodes(tree):
                if isinstance(node, ast.FunctionDef):
                    args = [a.arg for a in node.args.args]
                    lines.append(f"- **`{node.name}({', '.join(args)})`** (line {node.lineno})")
                    docstring = ast.get_docstring(node)
                    if docstring:
                        lines.append(f"  - {docstring.splitlines()[0]}")
                elif isinstance(node, ast.ClassDef):
                    lines.append(f"- **Class `{node.name}`** (line {node.lineno})")
                    docstring = ast.get_docstring(node)
                    if docstring:
                        lines.append(f"  - {docstring.splitlines()[0]}")
            lines.append("")

        lines.append("---")
        output_path = self.docs_dir / "api_reference.md"
        self.writer.write(output_path, "\n".join(lines))
        log.info(f"Generated API reference at {output_path}")
        return str(output_path)